version: '3.4'

services:
  gamehavenforum:
    image: ${DOCKER_REGISTRY-}gamehavenforum
    build:
      context: .
      dockerfile: GameHavenForum/Dockerfile
    ports:
        - "5001:80"

  dbforum:
    image: mysql:8.0
    container_name: dbforum
    restart: always
    ports:
       - '3307:3306'
    environment:
       MYSQL_DATABASE: gamehavenforum
       MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdataforum:/var/lib/mysql

  pmaforum:
      depends_on:
       - dbforum
      image: phpmyadmin/phpmyadmin
      container_name: pmaforum
      restart: always
      ports:
       - '8081:80'
      environment:
        PMA_HOST: dbforum


volumes:
  dbdataforum: